=== vaughnmb/GF4ProblemProject/billofmaterials/src/test/bomstructure.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bom (prn, bomdata)>
<!ELEMENT prn (#PCDATA)>
<!ELEMENT bomdata (bomentry+)>
 <!ELEMENT bomentry (row, depth, product-number, description, secondary-description,
  quantity, type-flag, last-ecn, ecn-date, obsolete, raw-material, 
  engineering-qty, required-qty, unit-of-measure)>
<!ELEMENT row (#PCDATA)>
<!ELEMENT depth (#PCDATA)>
<!ELEMENT product-number (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT secondary-description (#PCDATA)>
<!ELEMENT quantity (#PCDATA) >
<!ELEMENT type-flag (#PCDATA)>
<!ELEMENT last-ecn (#PCDATA)>
<!ELEMENT ecn-date (#PCDATA)>
<!ELEMENT obsolete (#PCDATA)>
<!ELEMENT raw-material (#PCDATA)>
<!ELEMENT engineering-qty (#PCDATA)>
<!ELEMENT required-qty (#PCDATA)>
<!ELEMENT unit-of-measure (#PCDATA)>

=== vaughnmb/GF4ProblemProject/billofmaterials/src/test/BomStructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bom PUBLIC "-//BillOfMaterials//BillOfMaterials DTD//EN" "http://iecapp0/dtd/bomstructure.dtd">
<bom>
	<prn>d065-00067914</prn>
	<bomdata>
		<bomentry>
			<row>1</row>
			<depth>0</depth>
			<product-number>D065-00067914</product-number>
			<description>RA PNL ASSY #1 M*Y03/04</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>			
			<required-qty></required-qty>			
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>
		<bomentry>
			<row>2</row>
			<depth>1</depth>
			<product-number>D065-00067895</product-number>
			<description>RA PNL #1 ADA M*Y03/04 ARC WHT</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>			
			<required-qty></required-qty>			
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>	
		<bomentry>
			<row>3</row>
			<depth>2</depth>
			<product-number>D065-00067896</product-number>
			<description>RA PNL #1 ADA M*Y03/04</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>
			<required-qty></required-qty>					
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>	
		<bomentry>
			<row>4</row>
			<depth>3</depth>
			<product-number>D065-00067897</product-number>
			<description>RA PNL #1 ADA M*Y03/04</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material>R035-70318000</raw-material>
			<engineering-qty>14.68</engineering-qty>
			<required-qty>17.61</required-qty>					
			<unit-of-measure>LB</unit-of-measure>
		</bomentry>
		<bomentry>
			<row>5</row>
			<depth>3</depth>
			<product-number>D125-90004259</product-number>
			<description>DECO PNL CLIP M*Y 300-1200</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material>R035-70318000</raw-material>
			<engineering-qty>0.38</engineering-qty>
			<required-qty>0.46</required-qty>						
			<unit-of-measure>LB</unit-of-measure>
		</bomentry>	
		<bomentry>
			<row>6</row>
			<depth>2</depth>
			<product-number>P000-70014816</product-number>
			<description>BKD PNT ARCT WHT</description>
			<secondary-description></secondary-description>
			<quantity>0</quantity>
			<type-flag>B</type-flag>
			<last-ecn>XX-XXXX</last-ecn>
			<ecn-date>MM/DD/YY</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>
			<required-qty></required-qty>						
			<unit-of-measure>LB</unit-of-measure>
		</bomentry>
		<bomentry>
			<row>7</row>
			<depth>1</depth>
			<product-number>D170-00067660</product-number>
			<description>PNL DECO INSUL 15.1X31.8</description>
			<secondary-description></secondary-description>
			<quantity>1</quantity>
			<type-flag>M</type-flag>
			<last-ecn>06-0960</last-ecn>
			<ecn-date>10/06/06</ecn-date>
			<obsolete>false</obsolete>
			<raw-material>R040-70012801</raw-material>
			<engineering-qty>3.39</engineering-qty>
			<required-qty>4.23</required-qty>						
			<unit-of-measure>SF</unit-of-measure>
		</bomentry>
		<bomentry>
			<row>8</row>
			<depth>1</depth>
			<product-number>G070-70019824</product-number>
			<description>CMLCK RTNR</description>
			<secondary-description></secondary-description>
			<quantity>2</quantity>
			<type-flag>B</type-flag>
			<last-ecn>XX-XXXX</last-ecn>
			<ecn-date>MM/DD/YY</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>
			<required-qty></required-qty>						
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>
		<bomentry>
			<row>9</row>
			<depth>1</depth>
			<product-number>G070-70019823</product-number>
			<description>CMLCK PAWL</description>
			<secondary-description></secondary-description>
			<quantity>2</quantity>
			<type-flag>B</type-flag>
			<last-ecn>XX-XXXX</last-ecn>
			<ecn-date>MM/DD/YY</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>
			<required-qty></required-qty>						
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>			
		<bomentry>
			<row>10</row>
			<depth>1</depth>
			<product-number>G070-70019837</product-number>
			<description>CMLCK SHFT HEX HEAD 2 IN</description>
			<secondary-description></secondary-description>
			<quantity>2</quantity>
			<type-flag>B</type-flag>
			<last-ecn>XX-XXXX</last-ecn>
			<ecn-date>MM/DD/YY</ecn-date>
			<obsolete>false</obsolete>
			<raw-material></raw-material>
			<engineering-qty></engineering-qty>
			<required-qty></required-qty>					
			<unit-of-measure>EA</unit-of-measure>
		</bomentry>			
	</bomdata>
</bom>
